name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    name: Build PHAR & publish release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: mbstring, json, yaml
          ini-values: phar.readonly=0
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # - name: Run tests
      #   run: php vendor/bin/pest --colors=never

      - name: Tests
        run: composer run test

      - name: Build PHAR
        run: vendor-bin/box/vendor/bin/box compile

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/index.php
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
